Add content API endpoints
DagsHub/openapi-description pull request #1
Opened 2022-09-28 13:20 UTC by idonov8

Adding new endpoints

2022-09-28 13:31 UTC, simonlsk requested changes

2022-09-28 13:31 UTC, simonlsk commented on components/schemas/File.yaml
> +  sha:
I think it's hash where does the sha come from?

2022-09-28 13:31 UTC, simonlsk commented on spec.yaml
> +        **`last_commit`** - If the tip of the branch differs on the server at the moment of processing the request, the request is denied.
Actually if the upload contains only new files, then `last_commit` is not mandatory and won't be "denied".

2022-09-28 13:38 UTC, idonov8 commented on components/schemas/File.yaml
> +  sha:
The response I got when testing had `sha`

2022-09-29 08:07 UTC, simonlsk commented on components/schemas/File.yaml
> +  sha:
You're right

2022-09-29 08:07 UTC, simonlsk commented on components/schemas/File.yaml
> +  sha:
We need to fix that

2022-09-29 08:11 UTC, simonlsk commented on components/schemas/File.yaml
> +  sha:
PR open - https://github.com/DagsHub/gogs/pull/1007

2022-09-29 08:11 UTC, simonlsk approved these changes

2022-10-31 14:25 UTC, merged