Add experiment api
DagsHub/openapi-description pull request #3
Opened 2022-10-23 14:21 UTC by idonov8

Will look like that:
![Screen Shot 2022-10-23 at 17 20 26](https://user-images.githubusercontent.com/15911452/197397348-dbd8a6c7-511d-4a03-b62e-15c09a5c6e5d.png)

2022-10-24 07:34 UTC, guysmoilov commented
What about the APIs to fetch the list of experiments of a repo, and the metric histories of an experiment?
Without at least the first one, how are you supposed to know the experiment key?

2022-10-24 08:45 UTC, simonlsk commented on spec.yaml
> +  /experiments/experiment/{experimentKey}/name:
What about get experiments?

2022-11-02 11:54 UTC, guysmoilov requested changes

2022-11-02 11:54 UTC, guysmoilov commented on spec.yaml
> +              example: "Awesome New Experiment Name"
This endpoint description is now inaccurate - it's now a general puprpose "edit experiment" API endpoint, that only allows editing the name for now

2022-11-02 11:54 UTC, guysmoilov commented on components/schemas/ExperimentNamePost.yaml
> +  - name
File should be renamed to reflect that it's a general Edit POST now.

2022-11-02 11:54 UTC, guysmoilov commented on components/parameters/ExperimentName.yaml
> +  type: string
Seems to be unused now

2022-11-02 11:54 UTC, guysmoilov commented on spec.yaml
> +  - url: http://localhost:3000/api/v1/
```suggestion
```

2022-11-02 12:03 UTC, guysmoilov approved these changes

2022-11-02 12:03 UTC, merged